# Generated by Django 5.1.6 on 2025-05-19 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.CharField(blank=True, default='20 May 2025', max_length=100),
        ),
    ]
